### ISSUE TITLE
all files are dumped in one folder

### ISSUE THREAD

**Issue by Semdevmaster** [cosminlupu/npmfiles#3]
How to get all dependencies in your own folders?
Now all files are dumped in one folder.

**Comment by cosminlupu** [comment]
This library does not handle moving the files to any folder, it only gathers a list of paths from the main files of your npm dependencies. Please read the [README.md](../blob/master/README.md) for more info on usage.

**Comment by joris-lambrechts** [comment]
@arsentver: I just switched over from bower and had the same issue. You need to specify the `base` property for the `src()` method:

```js
gulp.task('npm:main', function () {
    return gulp
        .src(mainNPMFiles({showWarnings: true}), {base: __dirname + '/node_modules'})
        .pipe(gulp.dest(__dirname + 'app/lib/npm'));
});
```
